services:
  openvscodegpu:
    container_name: openvscodegpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    image: openvscodegpu #gitpod/openvscode-server 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "11000:3000" # Expose the default port of ollama
      - "8080:8080"
    volumes:
      - ./BACKEND:/home/workspace:cached # Mount the custom model directory
    user: root
    init: true
    # stdin_open: true
    # tty: true